# release-drafter configuration
# ref: https://github.com/release-drafter/release-drafter#configuration
name-template: "v$RESOLVED_VERSION 🌈"
tag-template: "v$RESOLVED_VERSION"
exclude-labels:
  - "release"
  - "auto"
categories:
  - title: "🚀 Features"
    labels:
      - "feature"
  - title: "✨ Enhancements"
    labels:
      - "enhancement"
  - title: "🐛 Bug Fixes"
    labels:
      - "bugfix"
  - title: "👷 Fixes"
    labels:
      - "fix"
  - title: "🧰 Maintenance"
    labels:
      - "chore"
  - title: "📦 Dependencies"
    labels:
      - "dependencies"
change-template: "- $TITLE @$AUTHOR (#$NUMBER)"
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
template: $CHANGES
