name: VSCode拡張をリリースする

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: node_modules をインストール
        run: yarn install --frozen-lockfile

      - name: VSCode拡張をリリース
        run: yarn publish:vsce
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}

      - name: git に user 情報を設定
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/$GITHUB_REPOSITORY
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: canary へチェックアウト
        uses: actions/checkout@v3
        with:
          ref: canary

      - name: main ブランチの変更を canary ブランチに反映
        run: |
          git config pull.rebase false
          git pull --allow-unrelated-histories origin main
          git push origin HEAD
