name: Pull Request のラベリングを検証する

on:
  pull_request:
    branches:
      - canary
    types:
      - opened
      - labeled
      - unlabeled

jobs:
  validate-pr:
    runs-on: ubuntu-latest
    steps:
      - name: ラベルを付けるように警告する
        if: |
          !contains(github.event.pull_request.labels.*.name, 'fix') &&
          !contains(github.event.pull_request.labels.*.name, 'bugfix') &&
          !contains(github.event.pull_request.labels.*.name, 'enhancement') &&
          !contains(github.event.pull_request.labels.*.name, 'chore') &&
          !contains(github.event.pull_request.labels.*.name, 'feature')
        run: |
          echo "::error::次のラベルを付けてください。 labels: fix, bugfix, enhancement, feature, chore"
          exit 1
